# Site settings
title: restart
header-img: img/home-bg.png
email: chrisjames.r@gmail.com
copyright_name: chrisjamesr
description: > # this means to ignore newlines until "baseurl:"
  A little closer every time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: chrsjr
github_username:  chrisjamesr
learn_profile: chrisjamesr
email_username: chrisjames.r@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
